
// Copyright 2023 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../../api/video/video_frame_buffer.h

package org.webrtc;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VideoFrameBufferType.NATIVE, VideoFrameBufferType.I420, VideoFrameBufferType.I420A,
    VideoFrameBufferType.I444, VideoFrameBufferType.I010, VideoFrameBufferType.NV12
})
@Retention(RetentionPolicy.SOURCE)
public @interface VideoFrameBufferType {
  int NATIVE = 0;
  int I420 = 1;
  int I420A = 2;
  int I444 = 3;
  int I010 = 4;
  int NV12 = 5;
}
