export const mediaConsume       : () => number;
export const mediaConsumerClose : () => number;
export const mediaConsumerPause : () => number;
export const mediaConsumerResume: () => number;
export const mediaProducerClose : () => number;
export const mediaProducerPause : () => number;
export const mediaProducerResume: () => number;
export const roomClientList     : () => number;
export const roomClose : () => number;
export const roomEnter : () => number;
export const roomExpel : () => number;
export const roomInvite: (json: string) => number;
export const roomLeave : () => number;
export const shutdown  : () => number;
export const registerSend   : (callback: (signal: string, body: string) => void)   => number;
export const registerRequest: (callback: (signal: string, body: string) => string) => number;
