server:
  port: 8888
  http2:
    enabled: true
  ssl:
    key-alias: taoyao
    key-store: classpath:taoyao.jks
    key-store-password: 123456
    key-password: 123456
  tomcat:
    thread:
      max: 256
      min-spare: 8
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
# servlet:
#   context-path: /taoyao
spring:
  profiles:
    active: local
  application:
    name: taoyao-signal-server
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  task:
    execution:
      pool:
        core-size: 8
        max-size: 128
        keep-alive: 60s
        queue-capacity: 100000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-scheduling-
taoyao:
  url: https://gitee.com/acgist/taoyao
  name: 桃夭信令服务
  version: 1.0.0
  description: 桃夭WebRTC信令服务
  timeout: 5000
  id:
    index: 0
    max-index: 999999
  # 媒体配置
  media:
    # 默认音频
    audio:
      format: OPUS
      sample-size: 16
      sample-rate: 32000
    # 默认视频
    video:
      format: H264
      bitrate: 1200
      frame-rate: 24
      resolution: 1920*1080
    # 4K：UD=UHD=4K
    ud-video:
      format: H264
      bitrate: 1600
      frame-rate: 30
      resolution: 4096*2160
    # 2K：QD=QHD=2K
    qd-video:
      format: H264
      bitrate: 1600
      frame-rate: 30
      resolution: 2560*1440
    # 超清视频：FD=FHD=1080P
    fd-video:
      format: H264
      bitrate: 1200
      frame-rate: 24
      resolution: 1920*1080
    # 高清视频：HD=720P
    hd-video:
      format: H264
      bitrate: 1000
      frame-rate: 18
      resolution: 1280*720
    # 标清视频：SD=480P
    sd-video:
      format: H264
      bitrate: 800
      frame-rate: 16
      resolution: 720*480
    # 媒体服务配置
    media-server-list:
      - media-id: media-local-a
        enabled: true
        host: localhost
        port: 4443
        schema: wss
        username: taoyao
        password: taoyao
      - media-id: media-local-z
        enabled: true
        host: localhost
        port: 4443
        schema: wss
        username: taoyao
        password: taoyao
    # 录像配置
    record-storage-path: /data/record
  # Socket信令
  socket:
    enabled: true
    host: 0.0.0.0
    port: 9999
    timeout: ${taoyao.timeout}
    queue-size: 100000
    thread-min: 4
    thread-max: 128
    thread-name-prefix: ${spring.application.name}-signal-
    keep-alive-time: 60000
    buffer-size: 2048
  # WebRTC配置：没有P2P所以不会用到
  webrtc:
    # STUN服务
    stun:
      - host: stun1.l.google.com
        port: 19302
      - host: stun2.l.google.com
        port: 19302
    # TURN服务：需要自己搭建coturn
    turn:
      - host: 192.168.8.110
        port: 3478
        username: taoyao
        password: taoyao
      - host: 192.168.8.111
        port: 3478
        username: taoyao
        password: taoyao
  # 安全配置
  security:
    enabled: true
    realm: taoyao
    permit: /,/error,/index.html,/favicon.ico
    username: taoyao
    password: taoyao
  # 定时任务
  scheduled:
    media: 0 * * * * ?
    client: 0 * * * * ?
  # 脚本配置
  script:
    enabled: true
    media-reboot: pm2 restart taoyao-media-server
    media-shutdown: pm2 stop taoyao-media-server
    system-reboot: reboot
    system-shutdown: shutdown now
    platform-reboot: systemctl restart taoyao-signal-server
    platform-shutdown: systemctl stop taoyao-signal-server
