taoyao:
  media:
    media-server-list:
      - name: media-local-a
        enabled: true
        host: 192.168.1.110
        port: 4443
        schema: wss
        username: taoyao
        password: taoyao
  security:
    permit: /v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/,/error,/index.html,/favicon.ico