taoyao:
  media:
    media-server-list:
      - media-id: media-local-a
        enabled: false
        rewrite-ip: true
#       host: 192.168.1.110
        host: 192.168.8.110
        port: 9443
        schema: wss
        username: taoyao
        password: taoyao
  security:
    permit: /v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/,/error,/index.html,/favicon.ico