server:
  port: 8888
  http2:
    enabled: true
  ssl:
    key-alias: taoyao
    key-store: classpath:taoyao.jks
    key-store-password: 123456
    key-password: 123456
  tomcat:
    thread:
      max: 128
      min-spare: 4
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
# servlet:
#   context-path: /taoyao
spring:
  profiles:
    active: dev
  application:
    name: taoyao-server
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  task:
    execution:
      pool:
        core-size: 8
        max-size: 128
        keep-alive: 60s
        queue-capacity: 100000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-scheduling-
taoyao:
  url: https://gitee.com/acgist/taoyao
  name: 桃夭
  timeout: 5000
  version: 1.0.0
  description: WebRTC信令服务
  server-id: 1
  id:
    sn: 0
    max-index: 999999
  # 媒体配置
  media:
    audio:
      format: OPUS
      sample-size: 16
      sample-rate: 32000
    video:
      format: H264
      bitrate: 1200
      frame-rate: 24
      resolution: 1920*1080
    # 超清视频
    most-video:
      format: H264
      bitrate: 1200
      frame-rate: 24
      resolution: 1920*1080
    # 高清视频
    high-video:
      format: H264
      bitrate: 1000
      frame-rate: 18
      resolution: 1280*720
    # 标清视频
    norm-video:
      format: H264
      bitrate: 800
      frame-rate: 16
      resolution: 720*480
    # 流畅视频
    flow-video:
      format: H264
      bitrate: 600
      frame-rate: 16
      resolution: 640*480
  # WebRTC配置
  webrtc:
    # STUN服务
    stun:
      - stun:stun1.l.google.com:19302
      - stun:stun2.l.google.com:19302
      - stun:stun3.l.google.com:19302
      - stun:stun4.l.google.com:19302
    # TURN服务：coturn
    turn:
      - turn:127.0.0.1:8888
      - turn:127.0.0.1:8888
      - turn:127.0.0.1:8888
      - turn:127.0.0.1:8888
    # 信令服务配置
    signal:
      host: 192.168.1.100
      port: ${server.port:8888}
      schema: wss
      websocket: /websocket.signal
    # Mediasoup服务配置：可以部署多个简单实现负载均衡
    mediasoup-list:
      - host: 127.0.0.1
        #host: 192.168.8.110
        port: 4443
        schema: wss
        websocket: /websocket.signal
        username: taoyao
        password: taoyao
      - host: 127.0.0.1
        #host: 192.168.8.110
        port: 4443
        schema: wss
        websocket: /websocket.signal
        username: taoyao
        password: taoyao
  # 录像配置
  record:
    storage: /data/record
  # 安全配置
  security:
    enabled: true
    realm: taoyao
    permit: /,/error,/index.html,/favicon.ico
    username: taoyao
    password: taoyao
  # 定时任务
  scheduled:
    session: 0 * * * * ?
  # 集群节点
  node-list:
    - host: localhost
      port: 8888
      username: ${taoyao.security.username:taoyao}
      password: ${taoyao.security.username:taoyao}
      