server:
  port: 8888
  http2:
    enabled: true
  ssl:
    key-alias: taoyao
    key-store: classpath:taoyao.jks
    key-store-password: 123456
    key-password: 123456
  tomcat:
    thread:
      max: 128
      min-spare: 4
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
# servlet:
#   context-path: /taoyao
spring:
  profiles:
    active: dev
  application:
    name: taoyao-server
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  task:
    execution:
      pool:
        core-size: 8
        max-size: 128
        keep-alive: 60s
        queue-capacity: 100000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-scheduling-
taoyao:
  url: https://gitee.com/acgist/taoyao
  name: 桃夭
  timeout: 5000
  version: 1.0.0
  description: WebRTC信令服务
  id:
    sn: 0
    max-index: 999999
  # 媒体配置
  media:
    audio:
      format: OPUS
      sample-size: 16
      sample-rate: 32000
    video:
      format: H264
      bitrate: 1200
      frame-rate: 24
      resolution: 1280*760
    quality: high|standard|quick
  # WebRTC配置
  webrtc:
    # 架构模式
    framework: MESH
    # 媒体端口范围
    min-port: 45535
    max-port: 65535
    stun:
      - stun:stun1.l.google.com:19302
      - stun:stun2.l.google.com:19302
      - stun:stun3.l.google.com:19302
      - stun:stun4.l.google.com:19302
      - stun:stun.stunprotocol.org:3478
    turn:
      - stun:stun1.l.google.com:19302
      - stun:stun2.l.google.com:19302
      - stun:stun3.l.google.com:19302
      - stun:stun4.l.google.com:19302
      - stun:stun.stunprotocol.org:3478
    # KMS服务配置
    kms:
      host: 192.168.1.100
      port: 18888
      schema: wss
      websocket: /websocket.signal
      username: username
      password: password
    # 信令服务配置
    signal:
      host: 192.168.1.100
      port: ${server.port:8888}
      schema: wss
      websocket: /websocket.signal
  record:
    storage: /data/record
  security:
    enabled: true
    realm: taoyao
    permit: /v3/api-docs/,/swagger-ui/,/swagger-ui.html,/favicon.ico,/error
    username: taoyao
    password: taoyao
  scheduled:
    session: 0 * * * * ?
