server:
  port: 8888
  http2:
    enabled: true
  ssl:
    key-alias: taoyao
    key-store: classpath:taoyao.jks
    key-store-password: 123456
    key-password: 123456
  tomcat:
    thread:
      max: 128
      min-spare: 4
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
spring:
  profiles:
    active: dev
  application:
    name: taoyao-server
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  task:
    execution:
      pool:
        core-size: 8
        max-size: 128
        keep-alive: 60s
        queue-capacity: 100000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-
    scheduling:
      pool:
        size: 4
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: ${spring.application.name}-scheduling-
taoyao:
  url: https://gitee.com/acgist/taoyao
  name: 桃夭
  timeout: 5000
  version: 1.0.0
  description: WebRTC信令服务
  id:
    sn: 0
    max-index: 999999
  webrtc:
    type: SFU
    stun:
      - stun:stun1.l.google.com:19302
      - stun:stun2.l.google.com:19302
      - stun:stun3.l.google.com:19302
      - stun:stun4.l.google.com:19302
      - stun:stun.stunprotocol.org:3478
    turn:
  record:
    storage: /data/record
  security:
    realm: taoyao
    permit: /v3/api-docs/,/swagger-ui/,/favicon.ico,/error
    username: taoyao
    password: taoyao
  scheduled:
    session: 0 * * * * ?
