@startuml

title Meeting

actor ClientA as ClientA
participant "Signal" as Signal
participant "Media" as Media
actor ClientB as ClientB
actor ClientC as ClientC

autonumber

ClientA -> Signal: 创建会议
activate Signal
activate ClientA
Signal -> ClientA: 创建会议
deactivate ClientA
Signal -> ClientB: 创建会议
Signal -> ClientC: 创建会议
deactivate Signal

ClientA -> Signal: 进入会议
activate Signal
Signal -> ClientB: ClientA进入会议
Signal -> ClientC: ClientA进入会议
deactivate Signal


@enduml